### ISSUE TITLE
No sound after wake from sleep

### ISSUE THREAD

**Issue by JosephDuffy** [geneccx/XonarSTDeluxeDriver#4]
I've been using the driver for a month or so now and I'm loving it. However, as mentioned in the README, there is no audio after waking from sleep.

One thing I have noted is that if the output is changed in System Preferences => Sound => Output between Xonar Speakers and Xonar Rear HP that the audible "click" is heard, which to me indicates that the output has changed, although no sound is actually output.

My knowledge of C++ is a little sparse, but I'd be happy to help in any way I can, although I might need a place to start ;)

**Comment by geneccx** [comment]
Unfortunately as I am no longer using this card in my Hackintosh I can't really investigate this issue further. There are a couple of workarounds that I used in the past:

1. Switch to any other audio device, then unload and reload the kext. Sometimes this crashes so be weary.
2. Just keep your computer awake and have the display sleep. It's not very eco-friendly though.

If anyone does end up figuring out a more permanent solution, I'd be happy to merge it. Otherwise you'll have to stick to the above.

**Comment by JosephDuffy** [comment]
I have had some success running `sudo kextunload /System/Library/Extensions/XonarSTDeluxeDriver.kext/; sudo kextload /System/Library/Extensions/XonarSTDeluxeDriver.kext/` after waking and switching to another output. I plan to put this in to a script at some point to enable automation. For now I am happy with this :)

Thanks for the info!
